### ISSUE TITLE
6.21 breaks hooks

### ISSUE THREAD

**Issue by pseudonym117** [Matviy/LeagueReplayHook#1]
It seems that the fingerprint of the hooked functions has changed, and now they are null after FindFunctions() is called.

I dont think i have a version of the older league exe, so it is difficult to compare exactly what changed in the files.

**Comment by Matviy** [comment]
I haven't looked into it yet, but they might have ditched Scaleform entirely now that they're releasing the official replay system. Would be a shame to lose this kind of accessibility though. I'll take a look in a bit and see what's up.

**Comment by Matviy** [comment]
Yeah it seems like they've made some non-trivial changes and the fscommand function is no longer present. Invoke still is still there seems like they're still using Scaleform. Luckily the data output from invoke can exist even if fscommand does not, so i changed it so that it won't close the process and still output data, even without fscommand. On debug this will show a warning each time, on release it will work silently.

Let me know if you have any issues with it. Thanks!

**Comment by pseudonym117** [comment]
sorry for super long delay in responding back to this, but it seems like it worked. on the next patch too, with the new spectator UI. so they havent ditched it completely yet.

**Comment by zhaoyeming** [comment]
I have been experimenting with it recently and it seems not working. Maybe because I’m using a different client build since I’m in China. I’ll try a NA client.

Meanwhile, does anyone happen to know it still works? Thanks!
